db:
    driver: PostgresDriver
    hosts: localhost,127.0.0.1
    password: pass
    url: postgres:5432
    username: ${username.value:postgres}
    pool:
        size: 12
        timeout: 10
    pools:
        - size: 1
          timeout: 1
        - size: 2
          timeout: 2
        - size: 3
          timeout: 3
    properties:
      first: 123
      second: 456
      third.value: hello

logging:
  level:
    root: INFO
    com.dmdev.spring.pool: INFO
    org.springframework.jdbc.core: TRACE
  file:
    name: dmdev.log
    path: /

spring:
  mvc:
    format:
      date: iso
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://192.168.1.179:5433/postgres
#    url: jdbc:postgresql://192.168.3.11:5433/postgres
#    url: jdbc:postgresql://192.168.67.226:5433/postgchrres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
      open-in-view: false